// Generated by gencpp from file rom_ekf_robot/MapData.msg
// DO NOT EDIT!


#ifndef ROM_EKF_ROBOT_MESSAGE_MAPDATA_H
#define ROM_EKF_ROBOT_MESSAGE_MAPDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace rom_ekf_robot
{
template <class ContainerAllocator>
struct MapData_
{
  typedef MapData_<ContainerAllocator> Type;

  MapData_()
    : header()
    , centers()
    , radii()  {
    }
  MapData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , centers(_alloc)
    , radii(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _centers_type;
  _centers_type centers;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _radii_type;
  _radii_type radii;





  typedef boost::shared_ptr< ::rom_ekf_robot::MapData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rom_ekf_robot::MapData_<ContainerAllocator> const> ConstPtr;

}; // struct MapData_

typedef ::rom_ekf_robot::MapData_<std::allocator<void> > MapData;

typedef boost::shared_ptr< ::rom_ekf_robot::MapData > MapDataPtr;
typedef boost::shared_ptr< ::rom_ekf_robot::MapData const> MapDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rom_ekf_robot::MapData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rom_ekf_robot::MapData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rom_ekf_robot::MapData_<ContainerAllocator1> & lhs, const ::rom_ekf_robot::MapData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.centers == rhs.centers &&
    lhs.radii == rhs.radii;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rom_ekf_robot::MapData_<ContainerAllocator1> & lhs, const ::rom_ekf_robot::MapData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rom_ekf_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rom_ekf_robot::MapData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rom_ekf_robot::MapData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rom_ekf_robot::MapData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rom_ekf_robot::MapData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rom_ekf_robot::MapData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rom_ekf_robot::MapData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rom_ekf_robot::MapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad14deec1ca094129d74da465e115243";
  }

  static const char* value(const ::rom_ekf_robot::MapData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad14deec1ca09412ULL;
  static const uint64_t static_value2 = 0x9d74da465e115243ULL;
};

template<class ContainerAllocator>
struct DataType< ::rom_ekf_robot::MapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rom_ekf_robot/MapData";
  }

  static const char* value(const ::rom_ekf_robot::MapData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rom_ekf_robot::MapData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"geometry_msgs/Point[] centers\n"
"float64[] radii\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::rom_ekf_robot::MapData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rom_ekf_robot::MapData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.centers);
      stream.next(m.radii);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MapData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rom_ekf_robot::MapData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rom_ekf_robot::MapData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "centers[]" << std::endl;
    for (size_t i = 0; i < v.centers.size(); ++i)
    {
      s << indent << "  centers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.centers[i]);
    }
    s << indent << "radii[]" << std::endl;
    for (size_t i = 0; i < v.radii.size(); ++i)
    {
      s << indent << "  radii[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.radii[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROM_EKF_ROBOT_MESSAGE_MAPDATA_H
