plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: obstacles,        type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}



#robot with radius = .16
footprint: [[-0.16, 0], [-0.113137, -0.113137], [0, -0.16], [0.113137, -0.113137],
                [0.16, 0], [0.113137, 0.113137], [0, 0.16], [-0.113137, 0.113137]]



global_frame: map
robot_base_frame: base_link
resolution: .1
update_frequency: 7
publish_frequency: 7
transform_tolerance: 0.02
rolling_window: false
static_map: false
always_send_full_costmap: true


static_layer:
    map_topic: map
    unknown_cost_value: -1
    lethal_cost_threshold: 100
    first_map_only: true
    subscribe_to_updates: false

obstacles:
    observation_sources: scan
    scan: {data_type: LaserScan, sensor_frame: base_scan, clearing: true, marking: true, topic: scan}

# *************************************************************************************************
